name: "CI actions: Build, Lint and Test"

on:
  push:
    branches: [main, "lens-v2"]
  pull_request:
    branches: [main, "lens-v2"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - run: pnpm lint

      # - name: Run tests
      #   run: pnpm test
      #   env:
      #     SDK_GATED_TEST_PK: ${{secrets.SDK_GATED_TEST_PK}}
      #     SDK_GATED_TEST_PROFILE_ID: ${{secrets.SDK_GATED_TEST_PROFILE_ID}}
      #     SDK_GATED_TEST_PUBLICATION_ID: ${{secrets.SDK_GATED_TEST_PUBLICATION_ID}}
      #     TESTING_ENV_URL: ${{secrets.TESTING_ENV_URL}}
      #     TESTING_HEADER_KEY: ${{secrets.TESTING_HEADER_KEY}}
      #     TESTING_HEADER_VALUE: ${{secrets.TESTING_HEADER_VALUE}}

      - run: pnpm lint:examples

  docs:
    name: "Create & publish documentation"
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: docs
      - name: Setup pnpm for docs
        uses: pnpm/action-setup@v2.2.4

      - name: Use Node.js for docs
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: pnpm typedoc

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: docs
          folder: docs
